### ISSUE TITLE
Deployment is stuck in pending due to not enough resources.

### ISSUE THREAD

**Issue by yash7817** [vladikr/logsviewer#21] opened 2023-06-05 12:53 UTC
Is it a prerequisite to have 32GB memory free in nodes for these pods to run? I am currently having 30 GB of free memory causing deployment to fail. 

~~~
4m5s        Warning   FailedScheduling        pod/logsviewer-27ctdy                        0/3 nodes are available: 3 persistentvolumeclaim "elasticsearch-27ctdy" not found. preemption: 0/3 nodes are available: 3 Preemption is not helpful for scheduling.
4m4s        Warning   FailedScheduling        pod/logsviewer-27ctdy                        0/3 nodes are available: 3 Insufficient memory. preemption: 0/3 nodes are available: 3 No preemption victims found for incoming pod.
4m1s        Warning   FailedScheduling        pod/logsviewer-27ctdy                        0/3 nodes are available: 3 Insufficient memory. preemption: 0/3 nodes are available: 3 No preemption victims found for incoming pod.
~~~

**Comment by sradco** [comment] 2023-06-11 10:56
@vladikr PTAL

**Comment by vladikr** [comment] 2023-08-15 15:26
@yash7817 was this issue resolved? I remember something about s confusion regarding the availability of a storage class in the cluster... 
I'm not sure whether this is still an issue.

**Comment by machadovilaca** [comment] 2023-09-20 14:33
@yash7817 was the issue really memory availability or anything else?

@vladikr is it is really memory, I think we should close this as not a bug!

**Closed** 2023-09-23 07:23 UTC
